export const BRAND_DOMAINS: Record<string, string> = {
  // ─── LUXURY ITALIAN ───────────────────────────────────────────────
  "gucci.com": "Gucci",
  "prada.com": "Prada",
  "miumiu.com": "Miu Miu",
  "bottegaveneta.com": "Bottega Veneta",
  "fendi.com": "Fendi",
  "valentino.com": "Valentino",
  "versace.com": "Versace",
  "dolcegabbana.com": "Dolce & Gabbana",
  "ferragamo.com": "Ferragamo",
  "armani.com": "Giorgio Armani",
  "giorgioarmani.com": "Giorgio Armani",
  "emporioarmani.com": "Emporio Armani",
  "armaniexchange.com": "Armani Exchange",
  "maxmara.com": "Max Mara",
  "sportmax.com": "Sportmax",
  "marella.com": "Marella",
  "pennyblack.com": "Pennyblack",
  "weekendmaxmara.com": "Weekend Max Mara",
  "brunellocucinelli.com": "Brunello Cucinelli",
  "loropiana.com": "Loro Piana",
  "loro-piana.com": "Loro Piana",
  "zegna.com": "ZEGNA",
  "kiton.com": "Kiton",
  "canali.com": "Canali",
  "brioni.com": "Brioni",
  "etro.com": "Etro",
  "marni.com": "Marni",
  "moschino.com": "Moschino",
  "pinko.com": "Pinko",
  "liujo.com": "Liu Jo",
  "msgm.it": "MSGM",
  "msgm.com": "MSGM",
  "albertaferretti.com": "Alberta Ferretti",
  "philosophy.com": "Philosophy di Lorenzo Serafini",
  "emiliopucci.com": "Pucci",
  "roberto-cavalli.com": "Roberto Cavalli",
  "tods.com": "Tod's",
  "hogan.com": "Hogan",
  "fay.com": "Fay",
  "moncler.com": "Moncler",
  "stoneisl.com": "Stone Island",
  "stoneisland.com": "Stone Island",
  "cpcompany.com": "C.P. Company",
  "woolrich.com": "Woolrich",
  "napapijri.com": "Napapijri",
  "colmar.it": "Colmar",
  "colmar.com": "Colmar",
  "boggi.com": "Boggi Milano",
  "corneliani.com": "Corneliani",
  "ermanno-scervino.com": "Ermanno Scervino",
  "blumarine.com": "Blumarine",
  "missoni.com": "Missoni",
  "krizia.it": "Krizia",
  "furla.com": "Furla",
  "coccinelle.com": "Coccinelle",
  "pollini.com": "Pollini",
  "fragiacomo.com": "Fragiacomo",
  "casadei.com": "Casadei",
  "rene-caovilla.com": "René Caovilla",
  "aquazzura.com": "Aquazzura",
  "gianvitorossi.com": "Gianvito Rossi",
  "sergio-rossi.com": "Sergio Rossi",
  "giuseppezanotti.com": "Giuseppe Zanotti",
  "louboutin.com": "Christian Louboutin",
  "christianlouboutin.com": "Christian Louboutin",
  "manoloblahnik.com": "Manolo Blahnik",
  // ─── LUXURY FRENCH ────────────────────────────────────────────────
  "louisvuitton.com": "Louis Vuitton",
  "chanel.com": "Chanel",
  "dior.com": "Dior",
  "hermes.com": "Hermès",
  "celine.com": "Celine",
  "saintlaurent.com": "Saint Laurent",
  "ysl.com": "Saint Laurent",
  "balenciaga.com": "Balenciaga",
  "givenchy.com": "Givenchy",
  "loewe.com": "Loewe",
  "chloe.com": "Chloé",
  "isabelmarant.com": "Isabel Marant",
  "jacquemus.com": "Jacquemus",
  "ami-paris.com": "AMI Paris",
  "a-p-c.fr": "A.P.C.",
  "apc.fr": "A.P.C.",
  "commedesgarcons.com": "Comme des Garçons",
  "kenzo.com": "Kenzo",
  "lanvin.com": "Lanvin",
  "balmain.com": "Balmain",
  "maisoncmargiela.com": "Maison Margiela",
  "maisonmargiela.com": "Maison Margiela",
  "maison-alaia.com": "Alaïa",
  "alaia.com": "Alaïa",
  "rogervivier.com": "Roger Vivier",
  "repetto.com": "Repetto",
  "sezane.com": "Sézane",
  "rouje.com": "Rouje",
  "ba-sh.com": "ba&sh",
  "maje.com": "Maje",
  "sandro-paris.com": "Sandro",
  "iroparis.com": "IRO",
  "claudiepierlot.com": "Claudie Pierlot",
  "apairandaspare.com": "A Pair & A Spare",
  "americanvintage-store.com": "American Vintage",
  "essentiel-antwerp.com": "Essentiel Antwerp",
  "roamans.com": "Roamans",
  "vanessabruno.com": "Vanessa Bruno",
  "zadig-et-voltaire.com": "Zadig & Voltaire",
  "longchamp.com": "Longchamp",
  "lancel.com": "Lancel",
  "lacoste.com": "Lacoste",
  "courreges.com": "Courrèges",
  "carven.com": "Carven",
  "agneslb.com": "agnès b.",
  "gal-fer.com": "Galeries Lafayette",
  // ─── LUXURY BRITISH ───────────────────────────────────────────────
  "burberry.com": "Burberry",
  "alexandermcqueen.com": "Alexander McQueen",
  "mcqueen.com": "Alexander McQueen",
  "stellamccartney.com": "Stella McCartney",
  "viviennewestwood.com": "Vivienne Westwood",
  "jimmychoo.com": "Jimmy Choo",
  "mulberry.com": "Mulberry",
  "dunhill.com": "Dunhill",
  "hackett.com": "Hackett",
  "barbour.com": "Barbour",
  "jigsaw-online.com": "Jigsaw",
  "hobbs.co.uk": "Hobbs",
  "lkbennett.com": "L.K.Bennett",
  "reiss.com": "Reiss",
  "whistles.com": "Whistles",
  "phase-eight.com": "Phase Eight",
  "boden.co.uk": "Boden",
  "boden.com": "Boden",
  "fatface.com": "Fat Face",
  "joules.com": "Joules",
  "white-stuff.com": "White Stuff",
  // ─── LUXURY BELGIAN / DUTCH / NORDIC ──────────────────────────────
  "driesvannoten.com": "Dries Van Noten",
  "jilsander.com": "Jil Sander",
  "acnestudios.com": "Acne Studios",
  "toteme.com": "Toteme",
  "therow.com": "The Row",
  "arket.com": "Arket",
  "cos.com": "COS",
  "weekday.com": "Weekday",
  "stories.com": "& Other Stories",
  "monki.com": "Monki",
  "filippa-k.com": "Filippa K",
  "tigersofsweden.com": "Tigers of Sweden",
  "nudiejeans.com": "Nudie Jeans",
  "apc.com": "A.P.C.",
  "ganni.com": "Ganni",
  "stine-goya.com": "Stine Goya",
  "by-malene-birger.com": "By Malene Birger",
  "samsoe.com": "Samsøe Samsøe",
  "iro.dk": "IRO",
  "gestuz.com": "Gestuz",
  "resume.dk": "Résumé",
  "inwear.com": "InWear",
  "part-two.com": "Part Two",
  "marccain.com": "Marc Cain",
  "marcain.com": "Marc Cain",
  // ─── LUXURY AMERICAN ──────────────────────────────────────────────
  "ralphlauren.com": "Ralph Lauren",
  "pologrl.com": "Polo Ralph Lauren",
  "calvinklein.com": "Calvin Klein",
  "donnakaran.com": "Donna Karan",
  "dkny.com": "DKNY",
  "marcjacobs.com": "Marc Jacobs",
  "michaelkors.com": "Michael Kors",
  "katespade.com": "Kate Spade",
  "toryburch.com": "Tory Burch",
  "coach.com": "Coach",
  "coach.eu": "Coach",
  "stuartweitzman.com": "Stuart Weitzman",
  "theory.com": "Theory",
  "vince.com": "Vince",
  "equipmentfr.com": "Equipment",
  "jcrew.com": "J.Crew",
  "madewell.com": "Madewell",
  "clubmonaco.com": "Club Monaco",
  "tommyhilfiger.com": "Tommy Hilfiger",
  "tommy.com": "Tommy Hilfiger",
  "versaceusa.com": "Versace",
  "thakoon.com": "Thakoon",
  "proenzaschouler.com": "Proenza Schouler",
  "3-1philliplim.com": "3.1 Phillip Lim",
  "alexanderwang.com": "Alexander Wang",
  "oscardelarenta.com": "Oscar de la Renta",
  "carolinaherrera.com": "Carolina Herrera",
  "dvf.com": "Diane von Furstenberg",
  "zimmermann.com": "Zimmermann",
  "aliceandolivia.com": "Alice + Olivia",
  "tory-sport.com": "Tory Sport",
  "rebeccaminkoff.com": "Rebecca Minkoff",
  "mcmworldwide.com": "MCM",
  "mcm.com": "MCM",
  "mossvalentine.com": "Moss Valentine",
  // ─── STREETWEAR & CONTEMPORARY ────────────────────────────────────
  "off---white.com": "Off-White",
  "offwhite.com": "Off-White",
  "palmangels.com": "Palm Angels",
  "fearofgod.com": "Fear of God",
  "essentialsfearofgod.com": "Fear of God ESSENTIALS",
  "rhude.com": "Rhude",
  "representclo.com": "REPRESENT",
  "ambush-official.com": "AMBUSH",
  "sacai.jp": "Sacai",
  "kith.com": "Kith",
  "supremenewyork.com": "Supreme",
  "supreme.com": "Supreme",
  "bape.com": "A Bathing Ape",
  "abathingape.com": "A Bathing Ape",
  "aape.com": "AAPE",
  "palace-skateboards.com": "Palace",
  "thesoloist.jp": "The Soloist",
  "clot.com": "CLOT",
  "mastermind-japan.com": "mastermind JAPAN",
  "junyawatanabe.com": "Junya Watanabe",
  "undercover.co.jp": "Undercover",
  "yvminamoto.com": "Yohji Yamamoto",
  "yohjiyamamoto.co.jp": "Yohji Yamamoto",
  "isseymiyake.com": "Issey Miyake",
  "pleatsplease.com": "Pleats Please Issey Miyake",
  "comme-des-garcons.com": "Comme des Garçons",
  "needles.jp": "Needles",
  "engineeredgarments.com": "Engineered Garments",
  "nonnative.com": "Nonnative",
  "wtaps.com": "WTAPS",
  // ─── HIGH STREET / FAST FASHION ───────────────────────────────────
  "zara.com": "Zara",
  "zarahome.com": "Zara Home",
  "hm.com": "H&M",
  "mango.com": "Mango",
  "massimodutti.com": "Massimo Dutti",
  "pullandbear.com": "Pull&Bear",
  "bershka.com": "Bershka",
  "stradivarius.com": "Stradivarius",
  "oysho.com": "Oysho",
  "lefties.com": "Lefties",
  "asos.com": "ASOS",
  "boohoo.com": "Boohoo",
  "prettylittlething.com": "PrettyLittleThing",
  "missguided.com": "Missguided",
  "nastygal.com": "Nasty Gal",
  "shein.com": "SHEIN",
  "romwe.com": "ROMWE",
  "zaful.com": "ZAFUL",
  "uniqlo.com": "Uniqlo",
  "muji.com": "MUJI",
  "muji.eu": "MUJI",
  "next.co.uk": "Next",
  "next.com": "Next",
  "marksandspencer.com": "Marks & Spencer",
  "debenhams.com": "Debenhams",
  "riverisland.com": "River Island",
  "newlook.com": "New Look",
  "dorothyperkins.com": "Dorothy Perkins",
  "topshop.com": "Topshop",
  "miss-selfridge.com": "Miss Selfridge",
  "wallis-fashion.com": "Wallis",
  "warehouse.co.uk": "Warehouse",
  "oasis-stores.com": "Oasis",
  "frenchconnection.com": "French Connection",
  "allsaints.com": "AllSaints",
  "ted-baker.com": "Ted Baker",
  "tedbaker.com": "Ted Baker",
  "selfridges.com": "Selfridges",
  "libertylondon.com": "Liberty London",
  // ─── AMERICAN CASUAL ──────────────────────────────────────────────
  "abercrombie.com": "Abercrombie & Fitch",
  "hollisterco.com": "Hollister",
  "ae.com": "American Eagle",
  "aeo.com": "American Eagle",
  "urbanoutfitters.com": "Urban Outfitters",
  "anthropologie.com": "Anthropologie",
  "freepeople.com": "Free People",
  "bananarepublic.com": "Banana Republic",
  "gap.com": "GAP",
  "oldnavy.com": "Old Navy",
  "loft.com": "LOFT",
  "anntaylor.com": "Ann Taylor",
  "express.com": "Express",
  "forever21.com": "Forever 21",
  "charlotterusse.com": "Charlotte Russe",
  "h-and-m.com": "H&M",
  // ─── DENIM ────────────────────────────────────────────────────────
  "levi.com": "Levi's",
  "diesel.com": "Diesel",
  "pepejeans.com": "Pepe Jeans",
  "g-star.com": "G-Star RAW",
  "7forallmankind.com": "7 For All Mankind",
  "agjeans.com": "AG Jeans",
  "frame-store.com": "FRAME",
  "citizensofhumanity.com": "Citizens of Humanity",
  "motherdenim.com": "MOTHER",
  "closed.com": "Closed",
  "mottobike.com": "Motto",
  "wrangler.com": "Wrangler",
  "lee.com": "Lee",
  "tommyjeans.com": "Tommy Jeans",
  "calvinklein-jeans.com": "Calvin Klein Jeans",
  "replay.it": "Replay",
  "replay.com": "Replay",
  "dondup.com": "Dondup",
  "jacob-cohen.com": "Jacob Cohën",
  "paige.com": "PAIGE",
  "notdenim.com": "Not Denim",
  "ksubi.com": "Ksubi",
  "nudie.com": "Nudie Jeans",
  "abrand.com": "A Brand",
  "warpwefts.com": "Warp + Weft",
  // ─── SUSTAINABLE / CONTEMPORARY ───────────────────────────────────
  "reformation.com": "Reformation",
  "everlane.com": "Everlane",
  "na-kd.com": "NA-KD",
  "meshki.com": "MESHKI",
  "houseofcb.com": "House of CB",
  "ohpolly.com": "Oh Polly",
  "realisation-par.com": "Réalisation Par",
  "loq.com": "LOQ",
  "loefflerrandall.com": "Loeffler Randall",
  "lisou.co.uk": "Lisou",
  "byvarga.com": "By Varga",
  "doen.com": "DÔEN",
  "rhode.com": "Rhode",
  "rodalink.com": "Rodalink",
  "ahluwaliaofficial.com": "Ahluwalia",
  "patou.com": "Patou",
  "coperni.com": "Coperni",
  "ludovic-del.com": "Ludovic de Saint Sernin",
  "roksanda.com": "Roksanda",
  "emiliawickstead.com": "Emilia Wickstead",
  "erdem.com": "Erdem",
  "shrimps.com": "Shrimps",
  "rejina-pyo.com": "Rejina Pyo",
  "rianna-and-nina.com": "Rianna + Nina",
  "simonerocha.com": "Simone Rocha",
  "victoriabeckham.com": "Victoria Beckham",
  "roland-mouret.com": "Roland Mouret",
  "roksandailincic.com": "Roksanda",
  "motherschildrenclothing.com": "Mother",
  // ─── SPORTSWEAR & ACTIVEWEAR ──────────────────────────────────────
  "nike.com": "Nike",
  "adidas.com": "Adidas",
  "adidas.it": "Adidas",
  "puma.com": "Puma",
  "reebok.com": "Reebok",
  "newbalance.com": "New Balance",
  "asics.com": "ASICS",
  "on.com": "On",
  "on-running.com": "On",
  "hoka.com": "HOKA",
  "hokaoneone.com": "HOKA",
  "salomon.com": "Salomon",
  "underarmour.com": "Under Armour",
  "lululemon.com": "lululemon",
  "aloyoga.com": "Alo Yoga",
  "gymshark.com": "Gymshark",
  "vuori.com": "Vuori",
  "fabletics.com": "Fabletics",
  "athleta.com": "Athleta",
  "sweaty-betty.com": "Sweaty Betty",
  "sweatybetty.com": "Sweaty Betty",
  "varley.com": "Varley",
  "thenorthface.com": "The North Face",
  "arcteryx.com": "Arc'teryx",
  "patagonia.com": "Patagonia",
  "columbia.com": "Columbia",
  "fjallraven.com": "Fjällräven",
  "mammut.com": "Mammut",
  "haglofs.com": "Haglöfs",
  "marmot.com": "Marmot",
  "berghaus.com": "Berghaus",
  "rab.equipment": "Rab",
  "montbell.com": "mont-bell",
  "mizuno.com": "Mizuno",
  "brooks.com": "Brooks",
  "brooksrunning.com": "Brooks",
  "saucony.com": "Saucony",
  "altrarunning.com": "Altra",
  "inov-8.com": "Inov-8",
  "karrimor.com": "Karrimor",
  "decathlon.com": "Decathlon",
  "decathlon.it": "Decathlon",
  "kiprun.com": "Kiprun",
  "speedo.com": "Speedo",
  "arena.com": "Arena",
  "huub.com": "HUUB",
  "2xu.com": "2XU",
  "craft.se": "Craft",
  "kinetixx.com": "Kinetixx",
  "odlo.com": "Odlo",
  "falke.com": "FALKE",
  "compressport.com": "Compressport",
  "cepcompression.com": "CEP",
  "x-socks.com": "X-Socks",
  "giro.com": "Giro",
  "poc.com": "POC",
  // ─── SHOES ────────────────────────────────────────────────────────
  "drmartens.com": "Dr. Martens",
  "birkenstock.com": "Birkenstock",
  "vans.com": "Vans",
  "converse.com": "Converse",
  "timberland.com": "Timberland",
  "clarks.com": "Clarks",
  "ugg.com": "UGG",
  "newrock.com": "New Rock",
  "teva.com": "Teva",
  "keen.com": "KEEN",
  "merrell.com": "Merrell",
  "dansko.com": "Dansko",
  "ecco.com": "ECCO",
  "geox.com": "Geox",
  "superga.com": "Superga",
  "superga.it": "Superga",
  "camper.com": "Camper",
  "fitflop.com": "FitFlop",
  "crocs.com": "Crocs",
  "havaianas.com": "Havaianas",
  "sketchers.com": "Skechers",
  "skechers.com": "Skechers",
  "stevemadden.com": "Steve Madden",
  "bcbg.com": "BCBG",
  "samedelman.com": "Sam Edelman",
  "naturalizer.com": "Naturalizer",
  "aerosoles.com": "Aerosoles",
  "bandolino.com": "Bandolino",
  "ninewest.com": "Nine West",
  "jrenee.com": "J. Renée",
  "betseyjohnson.com": "Betsey Johnson",
  "charlotteolympia.com": "Charlotte Olympia",
  "pedrogarcia.com": "Pedro Garcia",
  "prettyballerinas.com": "Pretty Ballerinas",
  "bally.com": "Bally",
  "dune-london.com": "Dune London",
  "kurt-geiger.com": "Kurt Geiger",
  "aldoshoes.com": "ALDO",
  "aldo.com": "ALDO",
  "callitspring.com": "Call It Spring",
  "fiorentini-baker.com": "Fiorentini+Baker",
  "santoni.com": "Santoni",
  "magnannishoes.com": "Magnanni",
  "carminashoemaker.com": "Carmina",
  "trickers.com": "Tricker's",
  "crockettandjones.com": "Crockett & Jones",
  "johnlobb.com": "John Lobb",
  "edwardgreen.co.uk": "Edward Green",
  "churchs.com": "Church's",
  "grenson.com": "Grenson",
  "loake.co.uk": "Loake",
  "meermin.es": "Meermin",
  "saintcrispin.com": "Saint Crispin's",
  "mephisto.com": "Mephisto",
  "gabor-shoes.com": "Gabor",
  "ara-shoes.eu": "ara",
  "semler-shoes.com": "Semler",
  // ─── JEWELRY & WATCHES ────────────────────────────────────────────
  "tiffany.com": "Tiffany & Co.",
  "cartier.com": "Cartier",
  "bulgari.com": "Bulgari",
  "bvlgari.com": "Bulgari",
  "chopard.com": "Chopard",
  "vancleefarepels.com": "Van Cleef & Arpels",
  "vancleefarpels.com": "Van Cleef & Arpels",
  "pomellato.com": "Pomellato",
  "dodo.it": "Dodo",
  "piaget.com": "Piaget",
  "davidyurman.com": "David Yurman",
  "pandora.net": "Pandora",
  "swarovski.com": "Swarovski",
  "mikimoto.com": "Mikimoto",
  "tasaki.co.jp": "Tasaki",
  "georgjensen.com": "Georg Jensen",
  "trollbeads.com": "Trollbeads",
  "thomas-sabo.com": "Thomas Sabo",
  "links-of-london.com": "Links of London",
  "monica-vinader.com": "Monica Vinader",
  "monicavinader.com": "Monica Vinader",
  "mejuri.com": "Mejuri",
  "anothermorrow.com": "Another Morrow",
  "gorjana.com": "Gorjana",
  "kendra-scott.com": "Kendra Scott",
  "alexisbittar.com": "Alexis Bittar",
  "marchon.com": "Marchon",
  "astleyclarke.com": "Astley Clarke",
  "missoma.com": "Missoma",
  "catbirdnyc.com": "Catbird",
  "maisonethereal.com": "Maison Ethereal",
  "wwake.com": "WWake",
  "prounis.com": "Prounis",
  "irenenesbit.com": "Irene Neuwirth",
  "irene-neuwirth.com": "Irene Neuwirth",
  "sophiebille-brahe.com": "Sophie Bille Brahe",
  "alitaghavi.com": "Ali Tagh Avi",
  "mariadoloresfernandez.com": "Maria Dolores",
  // ─── WATCHES ──────────────────────────────────────────────────────
  "rolex.com": "Rolex",
  "omegawatches.com": "Omega",
  "tagheuer.com": "TAG Heuer",
  "breitling.com": "Breitling",
  "iwc.com": "IWC",
  "audemarspiguet.com": "Audemars Piguet",
  "patek.com": "Patek Philippe",
  "patekphilippe.com": "Patek Philippe",
  "longines.com": "Longines",
  "tissot.com": "Tissot",
  "hamilton-watch.com": "Hamilton",
  "swatch.com": "Swatch",
  "fossil.com": "Fossil",
  "mvmt.com": "MVMT",
  "danielwellington.com": "Daniel Wellington",
  "seikowatches.com": "Seiko",
  "citizenwatch.com": "Citizen",
  "casiomobile.com": "Casio",
  "casio.com": "Casio",
  "garmin.com": "Garmin",
  "apple.com": "Apple",
  "samsung.com": "Samsung",
  "fitbit.com": "Fitbit",
  "hublot.com": "Hublot",
  "jlc.com": "Jaeger-LeCoultre",
  "jaeger-lecoultre.com": "Jaeger-LeCoultre",
  "vacheron-constantin.com": "Vacheron Constantin",
  "blancpain.com": "Blancpain",
  "ulysse-nardin.com": "Ulysse Nardin",
  "panerai.com": "Panerai",
  "officinepanerai.com": "Panerai",
  "tudorwatch.com": "Tudor",
  "glashuette-original.com": "Glashütte Original",
  "a-lange-soehne.com": "A. Lange & Söhne",
  "frederiqueconstant.com": "Frédérique Constant",
  "raymond-weil.com": "Raymond Weil",
  "zenith-watches.com": "Zenith",
  "rado.com": "Rado",
  "mido.com": "Mido",
  // ─── BAGS & ACCESSORIES ───────────────────────────────────────────
  "kors.com": "Michael Kors",
  "guess.com": "GUESS",
  "mansurgavriel.com": "Mansur Gavriel",
  "a-cold-wall.com": "A-COLD-WALL*",
  "acoldwall.com": "A-COLD-WALL*",
  "medea.it": "Medea",
  "strathberry.com": "Strathberry",
  "polene-paris.com": "Polène",
  "polene.com": "Polène",
  "a-jevic.com": "A Jevic",
  "vasicparis.com": "Vasic",
  "byfarshoes.com": "BY FAR",
  "demellier.com": "DeMellier",
  "aspinalloflondon.com": "Aspinal of London",
  "smythson.com": "Smythson",
  "swaine-adeney.co.uk": "Swaine Adeney",
  "ghurka.com": "Ghurka",
  "billykirk.com": "Billykirk",
  "hardgraft.com": "hard graft",
  "mismo.dk": "Mismo",
  "mismo.com": "Mismo",
  "lotuff.com": "Lotuff",
  "saddlebackleather.com": "Saddleback Leather",
  "filson.com": "Filson",
  "frost-river.com": "Frost River",
  "tumi.com": "TUMI",
  "samsonite.com": "Samsonite",
  "rimowa.com": "RIMOWA",
  "monos.com": "MONOS",
  "awaytravel.com": "Away",
  "briggs-riley.com": "Briggs & Riley",
  // ─── LINGERIE & BEACHWEAR ─────────────────────────────────────────
  "victoriassecret.com": "Victoria's Secret",
  "hanky-panky.com": "Hanky Panky",
  "agentprovocateur.com": "Agent Provocateur",
  "rigbyandpeller.com": "Rigby & Peller",
  "aubade.com": "Aubade",
  "chantelle.com": "Chantelle",
  "simoneperele.com": "Simone Pérèle",
  "lascivious.com": "Lascivious",
  "cossabom.com": "Cossabom",
  "laperla.com": "La Perla",
  "fleur-du-mal.com": "Fleur du Mal",
  "figleaves.com": "Figleaves",
  "fantasie.com": "Fantasie",
  "freya.com": "Freya",
  "panache-lingerie.com": "Panache",
  "empreinte-lingerie.com": "Empreinte",
  "eres.fr": "Eres",
  "vix.com": "Vix",
  "onia.com": "ONIA",
  "heidi-klein.com": "Heidi Klein",
  "melissa-odabash.com": "Melissa Odabash",
  "aguabendita.com": "Agua Bendita",
  "triangl.com": "Triangl",
  "seafolly.com": "Seafolly",
  "itsalittlefishy.com": "It's a Little Fishy",
  "li-vy.com": "Livy",

  // ─── EYEWEAR ──────────────────────────────────────────────────────
  "rayban.com": "Ray-Ban",
  "oakley.com": "Oakley",
  "persol.com": "Persol",
  "oliverpeoples.com": "Oliver Peoples",
  "lindberg.com": "LINDBERG",
  "moscot.com": "MOSCOT",
  "warbyparker.com": "Warby Parker",
  "garrett-leight.com": "Garrett Leight",
  "cuttlershoe.com": "Cutler and Gross",
  "cutlerandgross.com": "Cutler and Gross",
  "thom-browne.com": "Thom Browne",
  "tomford.com": "Tom Ford",
  "porschedesign.com": "Porsche Design",
  "carrera.com": "Carrera",
  "silhouette.com": "Silhouette",
  "mykita.com": "MYKITA",
  "ic-berlin.com": "ic! berlin",
  "safilo.com": "Safilo",
  "luxottica.com": "Luxottica",
  // ─── MULTI-BRAND / DEPARTMENT STORES ──────────────────────────────
  "net-a-porter.com": "NET-A-PORTER",
  "mrporter.com": "MR PORTER",
  "mytheresa.com": "Mytheresa",
  "farfetch.com": "Farfetch",
  "ssense.com": "SSENSE",
  "matchesfashion.com": "MATCHES",
  "luisaviaroma.com": "LuisaViaRoma",
  "yoox.com": "YOOX",
  "theoutnet.com": "THE OUTNET",
  "shopbop.com": "Shopbop",
  "revolve.com": "REVOLVE",
  "intermixonline.com": "INTERMIX",
  "nordstrom.com": "Nordstrom",
  "nordstromrack.com": "Nordstrom Rack",
  "saksfifthavenue.com": "Saks Fifth Avenue",
  "neimanmarcus.com": "Neiman Marcus",
  "bergdorfgoodman.com": "Bergdorf Goodman",
  "harveynichols.com": "Harvey Nichols",
  "harrods.com": "Harrods",
  "brownsfashion.com": "Browns",
  "barneys.com": "Barneys",
  "colette.fr": "Colette",
  "antonioli.eu": "Antonioli",
  "biffi.com": "Biffi",
  "modes.com": "Modes",
  "leclaireur.com": "L'Eclaireur",
  "10corsocomo.com": "10 Corso Como",
  "larinascente.it": "La Rinascente",
  "coinclothing.com": "Coin",
  "ovs.it": "OVS",
  "oviesse.com": "OVS",
  "calzedonia.com": "Calzedonia",
  "intimissimi.com": "Intimissimi",
  "tezenis.com": "Tezenis",
  "terranova.eu": "Terranova",
  "benetton.com": "Benetton",
  "united-colors-of-benetton.com": "Benetton",
  "sisley.com": "Sisley",
};

/**
 * Sorted unique list of brand display names, for autocomplete UIs.
 */
export const BRAND_NAMES: string[] = Array.from(new Set(Object.values(BRAND_DOMAINS))).sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: "base" }),
);

/**
 * Extract brand name from a product URL.
 * Strips subdomains (www, www2, it., shop., etc.) and matches against BRAND_DOMAINS.
 */
export function getBrandFromUrl(url: string): string | null {
  try {
    const hostname = new URL(url).hostname.toLowerCase().replace(/^www\d*\./, "");
    if (BRAND_DOMAINS[hostname]) return BRAND_DOMAINS[hostname];

    // Try progressively shorter suffixes for subdomains like it.zara.com or shop.mango.com
    const parts = hostname.split(".");
    for (let i = 1; i < parts.length - 1; i++) {
      const suffix = parts.slice(i).join(".");
      if (BRAND_DOMAINS[suffix]) return BRAND_DOMAINS[suffix];
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Canonical key for comparing brand names across sources (wardrobe items,
 * saved profile brands, user input). Normalises: trim, lowercase, collapse
 * whitespace, strip diacritics and typographic apostrophes.
 */
export function canonicalBrandKey(name: string | null | undefined): string {
  return (name ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[\u2018\u2019\u02bc'`´]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}
